name: exkaldionline

on:
  push:
    branches: [ main, fix_installation]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: |
       sudo apt-get update 
       sudo apt-get install sox
    - name: Clone kaldi-asr
      run: |
       git clone https://github.com/kaldi-asr/kaldi
       cd kaldi
       git checkout acff3f65640715f22252f143df7c3e1997899163
    - name: Install MKL
      run: sudo ./kaldi/tools/extras/install_mkl.sh -sp debian intel-mkl-64bit-2019.2-057
    - name: Check Kaldi Dependencies
      run: ./kaldi/tools/extras/check_dependencies.sh
    - name: Build Kaldi's tools
      run: |
       cd kaldi/tools
       make -j 4
    - name: Build Kaldi's src
      run: |
       cd kaldi/src
       ./configure --shared --use-cuda=no
       make depend -j 4
       make -j 4
    - name: Add kaldi's bin to environment variables
      run: |
       for kaldi_path in `ls ./kaldi/src | grep bin | xargs -I{} readlink -e $KALDI_ROOT/src/{}`;do export PATH=$PATH:$kaldi_path; done
       env
