name: exkaldi_ubuntu_build

on:
  push:
    branches: [ master ]
jobs:
  exkaldi-installation-test:
    needs: [build-kaldi]
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04,ubuntu-20.04]
        python-version: [3.6, 3.7, 3.8]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        bash quick_install.sh
